"""Pydantic data models for Phase 5C AI Investigation Layer."""

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class AIInvestigationEvidence(BaseModel):
    """Compact deterministic evidence payload sent to the LLM."""

    metric: str
    anomaly_date: str
    baseline_period: str
    observed_value: float
    baseline_value: float
    absolute_change: float
    percentage_change: float | None
    direction: str
    orders_observed: float | None = None
    orders_baseline: float | None = None
    orders_change_pct: float | None = None
    aov_observed: float | None = None
    aov_baseline: float | None = None
    aov_change_pct: float | None = None
    volume_effect: float | None = None
    aov_effect: float | None = None
    interaction_effect: float | None = None
    top_contributors: list[dict[str, Any]] = Field(default_factory=list)
    operational_indicators: dict[str, Any] = Field(default_factory=dict)
    deterministic_summary: str
    limitations: str


class AIInvestigationResponse(BaseModel):
    """Structured executive report generated by the AI investigation layer."""

    investigation_title: str
    executive_summary: str
    key_findings: list[str]
    business_interpretation: list[str]
    recommended_actions: list[str]
    limitations: list[str]
    model: str
    generated_at: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
    is_fallback: bool = False
