"""Pydantic data models for Phase 5C AI Investigation Narrator."""

from typing import Literal

from pydantic import BaseModel, Field

from apps.analytics.investigation.models import InvestigationResponse


class InvestigationNarrative(BaseModel):
    """Structured executive narrative synthesizing verified numerical evidence."""

    title: str = Field(..., description="Concise narrative title")
    executive_summary: str = Field(
        ..., description="Executive summary of the investigation"
    )
    anomaly_statement: str = Field(
        ..., description="Statement of the observed change magnitude"
    )
    key_findings: list[str] = Field(
        default_factory=list,
        description="Core observations extracted from verified evidence",
    )
    root_causes: list[str] = Field(
        default_factory=list,
        description="Primary dimensional drivers contributing to KPI change",
    )
    contributing_factors: list[str] = Field(
        default_factory=list,
        description="Secondary and offsetting factors identified in breakdown",
    )
    recommended_next_steps: list[str] = Field(
        default_factory=list,
        description="Actionable business recommendations",
    )
    evidence_references: list[str] = Field(
        default_factory=list,
        description="Specific verified figures and percentages cited",
    )
    disclaimer: str = Field(
        ...,
        description="Statistical caveat distinguishing contribution from causal proof",
    )
    narrator_type: Literal["llm", "deterministic_fallback"] = Field(
        default="deterministic_fallback",
        description="Indicates whether generated by LLM or fallback narrator",
    )


class NarrativeRequest(BaseModel):
    """Request payload for generating an AI narrative."""

    investigation: InvestigationResponse
